import type { Metadata } from "next";
import "../styles/globals.css"; 
import localFont from "next/font/local";

const geistSans = localFont({
  src: "../../public/fonts/Geist-Regular.ttf", // ✅ Use relative path correctly
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMono-Regular.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Helina Belete",
  description: "Generated by Helina Belete",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
